- name: Install TimeKpr-nExT
  apt:
    name: timekpr-next
    state: present
    update_cache: yes
  become: true

- name: Ensure management user 'timekpr-remote' exists
  user:
    name: timekpr-remote
    groups: timekpr
    append: yes
    shell: /bin/bash
    create_home: yes
    state: present
  become: true

- name: Ensure .ssh directory exists for 'timekpr-remote'
  file:
    path: /home/timekpr-remote/.ssh
    state: directory
    mode: '0700'
    owner: timekpr-remote
    group: timekpr-remote
  become: true

- name: Install WebUI public key for timekpr-remote
  copy:
    src: timekpr_ui_key.pub
    dest: /home/timekpr-remote/.ssh/authorized_keys
    owner: timekpr-remote
    group: timekpr-remote
    mode: '0600'
  become: true
