- name: update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: autoremove packages
  apt:
    autoremove: yes
  become: true

- block:
    - name: check if flatpak exists
      stat:
        path: /usr/bin/flatpak
      register: flatpak_binary

    - name: ensure flathub remote exists
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      become: true
      ignore_errors: true

    - name: update all flatpak apps
      command: flatpak update -y --noninteractive
      become: true
      when: flatpak_binary.stat.exists

  rescue:
    - debug:
        msg: "Host offline oder Flatpak nicht vorhanden"

- block:
    - name: check if fwupd exists
      stat:
        path: /usr/bin/fwupdmgr
      register: fwupd_binary

    - name: install firmware updates
      command: fwupdmgr update -y
      become: true
      when: fwupd_binary.stat.exists

  rescue:
    - debug:
        msg: "Host offline oder fwupd nicht vorhanden"