- name: update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: autoremove packages
  apt:
    autoremove: yes

- name: check if flatpak exists
  stat:
    path: /usr/bin/flatpak
  register: flatpak_binary

- name: update flatpak apps
  command: flatpak update -y
  when: flatpak_binary.stat.exists

- name: check if fwupd exists
  stat:
    path: /usr/bin/fwupdmgr
  register: fwupd_binary

- name: install firmware updates
  command: fwupdmgr update -y
  when: fwupd_binary.stat.exists