- name: Update apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Autoremove
  apt:
    autoremove: yes
  become: true

- name: Get local users
  ansible.builtin.getent:
    database: passwd

- name: Update flatpak apps for all users
  ansible.builtin.command: flatpak update -y --noninteractive
  become: true
  become_user: "{{ item.key }}"
  loop: "{{ ansible_facts.passwd | dict2items }}"
  when:
    - "'flatpak' in ansible_facts.packages"
    - item.value.uid >= 1000
    - item.value.dir is defined
    - item.value.dir.startswith('/home/')

- name: Update firmware
  command: fwupdmgr update -y
  become: true
  when: ansible_facts.packages['fwupd'] is defined
