- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: install base packages
  apt:
    name:
      - curl
      - ca-certificates
      - git
      - nano
      - htop
      - zip
      - nala
    state: present
  become: true

- name: Refresh package facts
  ansible.builtin.package_facts:
  manager: auto