- name: install base packages
  apt:
    name:
      - curl
      - ca-certificates
      - git
      - nano
      - htop
      - zip
      - nala
    state: present
  become: true

- name: create user automation
  user:
    name: simon
    shell: /bin/bash
    groups: sudo
    state: present
  become: true