all:
  children:
  
    linux_servers:
      hosts:
        fileshare01:
          ansible_host: 192.168.1.20
          ansible_user: automation
          docker_enabled: true

        srv02:
          ansible_host: 10.10.10.12
          ansible_user: automation
          docker_enabled: false

    linux_desktops:
      hosts:
        desk01:
          ansible_host: 10.10.10.21
          ansible_user: automation

    windows_desktops:
      hosts:
        win01:
          ansible_host: 10.10.10.31
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_port: 5985