all:
  children:

    linux_desktops:
      hosts:
        simrah001: # XPS Simon
          ansible_host: 192.168.1.149
          ansible_user: simon
        simrah008: # Rahel
          ansible_host: 192.168.1.155
          ansible_user: localadmin
        samsung001: # Werkstatt
          ansible_host: 192.168.1.231
          ansible_user: simon

    edubuntu_clients:
      hosts:
        simrah002: #Marwin
          ansible_host: 192.168.1.160
          ansible_user: localadmin
        simrah003: #Matiss
          ansible_host: 192.168.1.152
          ansible_user: localadmin
        simrah004: #Anna
          ansible_host: 192.168.1.161
          ansible_user: localadmin
  
    linux_servers:
      hosts:
        fileshare01:
          ansible_host: 192.168.1.20
          ansible_user: localadmin
          docker_enabled: false
        druqshop001:
          ansible_host: 192.168.1.24
          ansible_user: localadmin
          docker_enabled: true
        ca001:
          ansible_host: 192.168.1.18
          ansible_user: localadmin
          docker_enabled: false
        demo001:
          ansible_host: 192.168.1.228
          ansible_user: localadmin
          docker_enabled: false
