- name: install docker dependencies
  apt:
    name:
      - docker.io
    state: present
  when: docker_enabled | default(false)
  become: true

- name: start docker
  service:
    name: docker
    state: started
    enabled: true
  when: docker_enabled | default(false)
  become: true