- name: apt basics
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: add onlyoffice key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE | gpg --dearmor -o /etc/apt/keyrings/onlyoffice.gpg

- name: add onlyoffice repo
  copy:
    dest: /etc/apt/sources.list.d/onlyoffice.list
    content: |
      deb [signed-by=/etc/apt/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install apt apps
  apt:
    name:
      - onlyoffice-desktopeditors
      - seafile-gui
    state: present
    update_cache: yes

- name: install flatpak
  apt:
    name: flatpak
    state: present

- name: install flatpak apps
  shell: |
    flatpak install -y flathub \
    com.bitwarden.desktop \
    org.localsend.localsend_app \
    com.github.iwalton3.jellyfin-media-player