- hosts: linux_desktops
  become: true
  ignore_unreachable: true
  roles:
    - common
    - linux_updates
    - linux_desktop
    - internal_ca

- hosts: edubuntu_clients
  become: true
  ignore_unreachable: true
  roles:
    - common
    - linux_updates
    - edubuntu_setup
    - internal_ca