- hosts: linux_servers
  become: true
  roles:
    - linux_updates_server
    - common
    - users_server
    - server_base
    - firewall
    - security
    - docker
    - role: step_ca
      when: step_ca_enabled | default(false)
    - monitoring